export const PRODUCT_REPOSITORY = Symbol('PRODUCT_REPOSITORY');
export const STORE_TRANSACTION_REPOSITORY = Symbol('STORE_TRANSACTION_REPOSITORY');
export const CUSTOMER_REPOSITORY = Symbol('CUSTOMER_REPOSITORY');
export const DELIVERY_REPOSITORY = Symbol('DELIVERY_REPOSITORY');
export const confidentielle_PAYMENT_PORT = Symbol('confidentielle_PAYMENT_PORT');
export const CHECKOUT_FINALIZE_PORT = Symbol('CHECKOUT_FINALIZE_PORT');
